--Create Tables

CREATE TABLE USER_TYPE (
    type_id INT IDENTITY(1,1) PRIMARY KEY,
    user_type VARCHAR(20),
    );

CREATE TABLE LOCATION (
    loc_id INT IDENTITY(1,1) PRIMARY KEY,
    loc_name VARCHAR(100),
    );

CREATE TABLE JOB_CATEGORY (
    cat_id INT IDENTITY(1,1) PRIMARY KEY,
    cat_name VARCHAR(100),
    );

CREATE TABLE SKILLS (
    skill_id INT IDENTITY(1,1) PRIMARY KEY,
    skill_name VARCHAR(100),
    );

CREATE TABLE USER_ACCOUNT (
    user_id INT IDENTITY(1,1) PRIMARY KEY,
    user_type INT NOT NULL FOREIGN KEY REFERENCES USER_TYPE(type_id) ON DELETE CASCADE,
    first_name VARCHAR (55),
    last_name VARCHAR (55),
    email VARCHAR (255),
    password VARCHAR (100),
    loc_id INT FOREIGN KEY REFERENCES LOCATION(loc_id),
    );

CREATE TABLE SEEKER_SKILLS(
    user_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id) ON DELETE CASCADE,
    skill_id INT NOT NULL FOREIGN KEY REFERENCES SKILLS(skill_id) ON DELETE CASCADE,
    PRIMARY KEY(user_id,skill_id),
    );

CREATE TABLE RECRUITER_PROFILE (
    user_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id) ON DELETE CASCADE,
    company_name VARCHAR(255),
);

CREATE TABLE EMPLOYMENT_TYPE (
    emp_type_id INT IDENTITY (1,1) PRIMARY KEY,
    emp_type_name VARCHAR(100),
);

CREATE TABLE SEEKER_EMPLOYMENT_TYPE (
    user_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id) ON DELETE CASCADE,
    emp_type_id INT NOT NULL FOREIGN KEY REFERENCES EMPLOYMENT_TYPE(emp_type_id) ON DELETE CASCADE,
    PRIMARY KEY(user_id,emp_type_id),
);

CREATE TABLE JOB_LISTING(
    job_id INT IDENTITY(1,1) PRIMARY KEY,
    poster_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id) ON DELETE CASCADE,
    posted_date DATE,
    title VARCHAR(255),
    employer VARCHAR(255),
    category INT NOT NULL FOREIGN KEY REFERENCES JOB_CATEGORY(cat_id) ON DELETE CASCADE,
    loc_id INT FOREIGN KEY REFERENCES LOCATION(loc_id) ON DELETE CASCADE,
    salary_min INT,
    salary_max INT,
    closing_date DATE,
    description VARCHAR(6000),
    status CHAR,
    );

SET DATEFORMAT dmy;

CREATE TABLE JOB_SKILLS(
    job_id INT NOT NULL FOREIGN KEY REFERENCES JOB_LISTING(job_id) ON DELETE CASCADE,
    skill_id INT NOT NULL FOREIGN KEY REFERENCES SKILLS(skill_id) ON DELETE CASCADE,
    PRIMARY KEY(job_id,skill_id),
    );

CREATE TABLE JOB_EMPLOYMENT_TYPE (
    job_id INT NOT NULL FOREIGN KEY REFERENCES JOB_LISTING(job_id) ON DELETE CASCADE,
    emp_type_id INT NOT NULL FOREIGN KEY REFERENCES EMPLOYMENT_TYPE(emp_type_id) ON DELETE CASCADE,
    PRIMARY KEY(job_id,emp_type_id),
);

CREATE TABLE APPLICATION (
    application_id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id),
    job_id INT NOT NULL FOREIGN KEY REFERENCES JOB_LISTING(job_id) ON DELETE CASCADE,
    application_date DATE NOT NULL,
    additional_comments VARCHAR(500),
    resume VARBINARY(MAX),
    cover_letter VARBINARY(MAX),
    additional_files VARBINARY(MAX),
);

CREATE TABLE MESSAGES (
    message_id INT IDENTITY (1,1) PRIMARY KEY,
    receiver_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id),
    sender_id INT NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(user_id),
    date DATE,
    subject VARCHAR(255),
    message VARCHAR(MAX),
    read_status BIT
);